version: "3.9"

services:
  undertow-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: undertow-app-container
    ports:
      - "8080:8080"
    volumes:
      - ../config.properties:/app/config.properties
      - undertow-mapdb:/app/db
    environment:
      - JAVA_OPTS=-Xmx512m

volumes:
  undertow-mapdb: